
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/rmdou/Desktop/TIER_LIST_PROGRAM_NEW/tools/cmake/cmake-3.31.6-windows-x86_64/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:6 (project)"
    message: |
      The system is: Windows - 10.0.26200 - AMD64
...
